spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/governdata
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.governdata: DEBUG
    org.hibernate.SQL: DEBUG
